### ISSUE TITLE
Verify tutorial

### ISSUE THREAD

**Issue by aaron-prindle** [grafeas/kritis#160] opened 2018-08-02 19:34 UTC
Verify Tutorial and add steps to push images to user project before running kritis

**Comment by tstromberg** [comment] 2018-08-07 18:00
Image pushing is a dupe of #148

**Comment by tstromberg** [comment] 2018-08-09 20:01
Tutorial now has steps to copy images into ones project. Tutorial has been run through a couple of times, and save for resolve-tags issues, seems to work.

**Closed by tstromberg** 2018-08-09 20:01 UTC
Labels: release-requirement
