### ISSUE TITLE
Kritis signer failed to create attestation

### ISSUE THREAD

**Issue by smeeklai** [grafeas/kritis#335] opened 2019-03-05 10:40 UTC
## Expected Behavior
Create an attestation successfully 
## Actual Behavior
```
Ceate attestation by "gcr.io/la-new-infra/central-builder@sha256:XXXXXXXXXXXXXXXXXXXXXXXXX" for "kritis-authority"
panic: interface conversion: interface is nil, not crypto.Signer

goroutine 1138 [running]:
github.com/grafeas/kritis/vendor/golang.org/x/crypto/openpgp/packet.(*Signature).Sign(0xc420724c40, 0x1432480, 0xc420482180, 0xc4202e69c0, 0x1c1ce20, 0xc420482180, 0x0)
	/go/src/github.com/grafeas/kritis/vendor/golang.org/x/crypto/openpgp/packet/signature.go:521 +0x121
github.com/grafeas/kritis/vendor/golang.org/x/crypto/openpgp/packet.(*Signature).SignUserId(0xc420724c40, 0x0, 0x0, 0xc4205a2280, 0xc4202e69c0, 0x1c1ce20, 0xc4204905c0, 0x410568)
	/go/src/github.com/grafeas/kritis/vendor/golang.org/x/crypto/openpgp/packet/signature.go:583 +0xb0
github.com/grafeas/kritis/pkg/kritis/attestation.createEntityFromKeys(0xc4205a2280, 0xc4202e69c0, 0xc4205d4000, 0x984, 0xc4204f24d0)
	/go/src/github.com/grafeas/kritis/pkg/kritis/attestation/attestation.go:155 +0x301
github.com/grafeas/kritis/pkg/kritis/attestation.CreateMessageAttestation(0xc4205d4000, 0x984, 0xc4205d6000, 0x1448, 0xc42018c4b0, 0xe5, 0x0, 0x0, 0xc420338c00, 0x40a450)
	/go/src/github.com/grafeas/kritis/pkg/kritis/attestation/attestation.go:101 +0x97
github.com/grafeas/kritis/pkg/kritis/util.CreateAttestationSignature(0xc42007a460, 0x6b, 0xc4205ce1b0, 0x0, 0xc420735638, 0x44280f, 0xc4205d6000)
	/go/src/github.com/grafeas/kritis/pkg/kritis/util/util.go:44 +0xd9
github.com/grafeas/kritis/pkg/kritis/metadata/containeranalysis.ContainerAnalysis.CreateAttestationOccurence(0xc420450090, 0x142e2c0, 0xc420044048, 0xc420536be0, 0xc42007a460, 0x6b, 0xc4205ce1b0, 0xc420536be0, 0x0, 0x0)
	/go/src/github.com/grafeas/kritis/pkg/kritis/metadata/containeranalysis/containeranalysis.go:211 +0x85
github.com/grafeas/kritis/pkg/kritis/gcbsigner.Signer.addAttestation(0xc4207a2ee0, 0x1432540, 0xc42079fdc0, 0xc42007a460, 0x6b, 0xc420798b79, 0x7, 0xc420798bc0, 0x10, 0x7, ...)
	/go/src/github.com/grafeas/kritis/pkg/kritis/gcbsigner/signer.go:106 +0x5ba
github.com/grafeas/kritis/pkg/kritis/gcbsigner.Signer.ValidateAndSign(0xc4207a2ee0, 0x1432540, 0xc42079fdc0, 0xc4205c4a50, 0x24, 0xc42007a460, 0x6b, 0xc4205c4c60, 0x2b, 0xc420359540, ...)
	/go/src/github.com/grafeas/kritis/pkg/kritis/gcbsigner/signer.go:70 +0x434
main.process(0xc42003c031, 0x7, 0xc4200e27e0, 0xc400000008, 0xc420079280)
	/go/src/github.com/grafeas/kritis/cmd/kritis/gcbsigner/main.go:90 +0x3cf
main.run.func1(0x142e280, 0xc420490dc0, 0xc4200e27e0)
	/go/src/github.com/grafeas/kritis/cmd/kritis/gcbsigner/main.go:56 +0x41
github.com/grafeas/kritis/vendor/cloud.google.com/go/pubsub.(*Subscription).receive.func3(0xc420583640, 0xc4202e2ce0, 0x142e280, 0xc420490dc0, 0xc4200e27e0)
	/go/src/github.com/grafeas/kritis/vendor/cloud.google.com/go/pubsub/subscription.go:509 +0x6a
created by github.com/grafeas/kritis/vendor/cloud.google.com/go/pubsub.(*Subscription).receive
	/go/src/github.com/grafeas/kritis/vendor/cloud.google.com/go/pubsub/subscription.go:507 +0x213
```

## Steps to Reproduce the Problem
Follow the [signer_install.md](https://github.com/grafeas/kritis/blob/master/docs/signer_install.md) document

Environment, commands

## Additional info
1.  Running on GKE
2.  Create everything in `default` namespace
3.  Using image `gcr.io/kritis-test1/kritis-gcb-signer:2440f7b6eeca3b208b891e7adbb304d7b008f7e5`
4.  A dedicated service account with `project owner` permission is created and used by the signer (just for the sake of debugging) 
5.  PGP keys and secret are created using below commands
 ```
gpg --quick-generate-key --yes my.attestator@example.com
gpg --armor --export my.attestator@example.com > gpg.pub
gpg --armor --export-secret-keys my.attestator@example.com > gpg.priv
kubectl create secret generic my-attestator --from-file=public=gpg.pub --from-file=private=gpg.priv --from-literal=passphrase=<passphrase>
```
6.  AttestationAuthority
```
apiVersion: kritis.grafeas.io/v1beta1
kind: AttestationAuthority
metadata:
  name: kritis-authority
  namespace: default
spec:
  noteReference: v1beta1/projects/la-new-infra
  privateKeySecretName: my-attestator
```
7. BuildPolicy
```
apiVersion: kritis.grafeas.io/v1beta1
kind: BuildPolicy
metadata:
  name: kritis-bp
  namespace: default
spec:
  attestationAuthorityName: kritis-authority
  buildRequirements:
    builtFrom: ".*"
```
8. **I successfully created an attestation manually by following this Google's [guide](https://cloud.google.com/binary-authorization/docs/getting-started-cli#create_an_attestation)**

**Comment by Jdubedition** [comment] 2019-05-09 21:38
It seems to be an issue with having "." or "-" in the name of the account.  When I used attestator@example.com instead of my.attestator@example.com, I was able to get past the error you reported.  I tried using the test-attestor@example.com from the Google example and that caused the crypto.Signer failure as well, so there appears to be an issue with hyphens.

**Comment by aysylu** [comment] 2019-07-26 19:07
Thanks for reporting, @smeeklai, and for the solution, @Jdubedition! Would either of you be interested in submitting a fix and a note about this to the documentation?

**Comment by iasinDev** [comment] 2019-08-02 11:16
Hi, I have a similar problem... that is that apparently failed to create attestation; the problem is that in the logs it didn't appear any problem


2019-08-02 12:30:23.187 CEST
Ceate attestation by "gcr.io/**********************************************************" for "kritis-authority"
Expand all | Collapse all {
 insertId:  "*******************"  
 labels: {…}  
 logName:  "**********************************************************/logs/kritis-gcb-signer"  
 receiveTimestamp:  "2019-08-02T10:30:25.808697686Z"  
 resource: {…}  
 severity:  "INFO"  
 textPayload:  "Ceate attestation by "gcr.io/**********************************************************" for "kritis-authority""  
 timestamp:  "2019-08-02T10:30:23.187875Z"  
}

And fetching attestations to GCP I didn't get any.

So... is there a way to debug this a little more to see if after this message kritis have some kind of ack of the attestation creation?

Thanks!

**Comment by iasinDev** [comment] 2019-08-02 21:47
As update to my last comment... I was using no passphrase in my PGP key. Seeing this issue, I tried using it, and now I'm in the same situation as @smeeklai with also the same setup (GKE, the installation guide, ...) but using no problematic characters according to @Jdubedition :

export ATTESTOR_NAME="attestor"
export ATTESTOR_EMAIL="attestor@example.com"

but getting the same error:

2019-08-02T20:12:01.181087Z Ceate attestation by "gcr.io/******************" for "kritis-authority" I 
2019-08-02T20:12:01.196325573Z panic: interface conversion: interface is nil, not crypto.Signer

goroutine 58 [running]:
github.com/grafeas/kritis/vendor/golang.org/x/crypto/openpgp/packet.(*Signature).Sign(0xc42*************************)
	/go/src/github.com/grafeas/kritis/vendor/golang.org/x/crypto/openpgp/packet/signature.go:521 +0x121
github.com/grafeas/kritis/vendor/golang.org/x/crypto/openpgp/packet.(*Signature).SignUserId(0xc42*************************)

But changing for example the passphrase I entered by instead of passing the one with:

export B64PHRASE=$( echo ${PHRASE} | base64)

just passing the simple

${PHRASE}

I get almost the slightly different same error:

goroutine 114 [running]:
github.com/grafeas/kritis/vendor/golang.org/x/crypto/openpgp/packet.(*Signature).Sign(0xc42*********************)
	/go/src/github.com/grafeas/kritis/vendor/golang.org/x/crypto/openpgp/packet/signature.go:521 +0x121
github.com/grafeas/kritis/vendor/golang.org/x/crypto/openpgp/packet.(*Signature).SignUserId(0xc42*********************)
	/go/src/github.com/grafeas/kritis/vendor/golang.org/x/crypto/openpgp/packet/signature.go:583 +0xb0
github.com/grafeas/kritis/pkg/kritis/attestation

So I'm a bit sure that is related with the kind in PGP key passed I think...

Please do you have any suggestion of it? I'm generating the key with that, based on the google manual of the attestor [here](https://cloud.google.com/binary-authorization/docs/getting-started-cli#create_an_attestation):

gpg --batch --gen-key <(
  cat <<- EOF
    Key-Type: RSA
    Key-Length: 2048
    Name-Real: "${ATTESTOR_NAME}"
    Name-Email: "${ATTESTOR_EMAIL}"
    Passphrase: ${PHRASE}
    %commit
EOF
)

gpg --armor --export "${ATTESTOR_EMAIL}" > /tmp/generated-key.pub

gpg --armor --export-secret-keys "${ATTESTOR_EMAIL}" > /tmp/generated-key-secret.priv


Thanks!

**Comment by codingandcoding** [comment] 2019-08-10 13:56
hello,I ran into the same problem when I used the following configuration.

gpg --quick-generate-key --yes attestor@example.com
gpg --armor --export attestor@example.com > gpg.pub
gpg --armor --export-secret-keys attestor@example.com > gpg.priv
PUBLIC_KEY=`base64 gpg.pub -w 0`
kubectl create secret generic attestor --from-file=public=gpg.pub --from-file=private=gpg.priv

warning: GOPATH set to GOROOT (/usr/lib/golang) has no effect
2019/08/10 19:02:58 Created note name:"projects/kritis/notes/att" short_description:"Generic Attestation Policy Attestor" long_description:"Generic Attestation Policy Attestor deployed in default namespace" create_time:<seconds:1565434978 nanos:506408983 > update_time:<seconds:1565434978 nanos:506408983 > attestation_authority:<hint:<human_readable_name:"attestation" > >  in project kritis
2019/08/10 19:02:58 Listing notes...
2019/08/10 19:02:58 [name:"projects/kritis/notes/att" short_description:"Generic Attestation Policy Attestor" long_description:"Generic Attestation Policy Attestor deployed in default namespace" create_time:<seconds:1565434978 nanos:506408983 > update_time:<seconds:1565434978 nanos:506408983 > attestation_authority:<hint:<human_readable_name:"attestation" > > ]
2019/08/10 19:02:58 Retrieved secret for 'attestor': &{0xc00037cb20 attestor}
2019/08/10 19:02:58 Created fingerprint: F51A1EFDA6A2B60230033CFD7ED98F12A0FDAEEB
panic: interface conversion: interface is nil, not crypto.Signer

goroutine 1 [running]:
github.com/grafeas/kritis/vendor/golang.org/x/crypto/openpgp/packet.(*Signature).Sign(0xc000124000, 0x141b7a0, 0xc00009e000, 0xc0000b4820, 0x1ea43c0, 0xc00009e000, 0x0)
	/usr/lib/golang/src/github.com/grafeas/kritis/vendor/golang.org/x/crypto/openpgp/packet/signature.go:521 +0x119
github.com/grafeas/kritis/vendor/golang.org/x/crypto/openpgp/packet.(*Signature).SignUserId(0xc000124000, 0x0, 0x0, 0xc00042a140, 0xc0000b4820, 0x1ea43c0, 0xc000389500, 0x8)
	/usr/lib/golang/src/github.com/grafeas/kritis/vendor/golang.org/x/crypto/openpgp/packet/signature.go:583 +0xb0
github.com/grafeas/kritis/pkg/kritis/attestation.createEntityFromKeys(0xc00042a140, 0xc0000b4820, 0x7f984bb28d80, 0x1187f21, 0xc000228000)
	/usr/lib/golang/src/github.com/grafeas/kritis/pkg/kritis/attestation/attestation.go:156 +0x2e3
github.com/grafeas/kritis/pkg/kritis/attestation.CreateMessageAttestation(0xc00037cb20, 0xc0002280f0, 0xe8, 0x0, 0x0, 0x0, 0x3d)
	/usr/lib/golang/src/github.com/grafeas/kritis/pkg/kritis/attestation/attestation.go:102 +0x4f
github.com/grafeas/kritis/pkg/kritis/util.CreateAttestationSignature(0x12fe307, 0x6e, 0xc0002b3ca0, 0x1, 0x1, 0x0, 0x0)
	/usr/lib/golang/src/github.com/grafeas/kritis/pkg/kritis/util/util.go:83 +0xa0
main.createOccRequest(0xc0000cbd90, 0x1)
	/usr/lib/golang/src/github.com/grafeas/kritis/docs/standalone/create_attestation.go:134 +0x1ee
main.main()
	/usr/lib/golang/src/github.com/grafeas/kritis/docs/standalone/create_attestation.go:95 +0x643
exit status 2

Can you find a solution?

**Comment by iasinDev** [comment] 2019-08-10 15:35
No sorry, finally I abandoned using passphrase in the PGP key cause I got stucked on this error...

Now I remain stucked also with the no passphrase option because I'm not able to retrieve the created attestations from GCP, but with no cripto error :-) (irony)

I'm thinking that the oficial release and the docker image of the tutorials (gcr.io ... ) maybe are not the same and the gcr one have previous bugs, but not sure...

**Comment by aysylu** [comment] 2019-08-12 18:29
Hello @iasinDev and @codingandcoding,

Could you please share your `gpg` version? I'm tracking a similar issue with the tooling in #372, so getting more information on this would be helpful to track the root cause.

Thanks!

**Comment by codingandcoding** [comment] 2019-08-12 23:58
Hello, the gpg version I am using is gpg 2.2.10

**Comment by codingandcoding** [comment] 2019-08-12 23:59
Hello @aysylu , the gpg version I am using is gpg 2.2.10

**Comment by iasinDev** [comment] 2019-08-19 08:16
Hi @aysylu sorry for the delay, gpg (GnuPG) 1.4.20

**Comment by liufangwai** [comment] 2020-12-21 12:01
was this problem fixed ?

**Comment by ooq** [comment] 2020-12-21 16:27
This issue is obsolete, as the previous gcbsigner is being re-implemented:
- for standalone signing tool, you can refer to [Kritis Signer](https://github.com/grafeas/kritis/blob/master/docs/signer.md)
- for automated signer that listens to GCR events, it's being merged in [this PR](https://github.com/grafeas/kritis/pull/595)

@liufangwai Do you come across similar issue with the current signer or just check in update on the previous signer?

Closing this issue for now. Feel free to create new one if there is similar issue with the new signer.

**Closed by ooq** 2020-12-21 16:27 UTC

**Comment by liufangwai** [comment] 2020-12-24 03:45
> This issue is obsolete, as the previous gcbsigner is being re-implemented:
> 
> * for standalone signing tool, you can refer to [Kritis Signer](https://github.com/grafeas/kritis/blob/master/docs/signer.md)
> * for automated signer that listens to GCR events, it's being merged in [this PR](https://github.com/grafeas/kritis/pull/595)
> 
> @liufangwai Do you come across similar issue with the current signer or just check in update on the previous signer?
> 
> Closing this issue for now. Feel free to create new one if there is similar issue with the new signer.

@ooq you are right , this problem was solved. i have verified this point.
